version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - manhunto
    assignees:
      - manhunto
    labels:
      - dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - manhunto
    assignees:
      - manhunto
    labels:
      - dependencies