version: "3.8"
services:
  rabbitmq:
    build:
      context: .
      dockerfile: .docker/rabbitmq/Dockerfile
      args:
        RABBITMQ_VERSION: "3.13.0"
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    privileged: true
    networks:
      - rabbitmq
  postgres:
    container_name: postgres
    image: postgres:16.3-alpine3.19
    ports:
      - "54320:5432"
    env_file:
      - .env
networks:
  rabbitmq:
    driver: bridge
