version: "3.8"
services:
  rabbitmq:
    build:
      context: .
      dockerfile: .docker/rabbitmq/Dockerfile
      args:
        RABBITMQ_VERSION: "3.13.0"
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    privileged: true
    networks:
      - rabbitmq
networks:
  rabbitmq:
    driver: bridge
