version: "3.8"
services:
  rabbitmq:
    container_name: rabbitmq
    build:
      context: .
      dockerfile: .docker/rabbitmq/Dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
    privileged: true
    networks:
      - rabbitmq
  postgres:
    container_name: postgres
    image: postgres:16.3-alpine3.20
    ports:
      - "5432:5432"
    env_file:
      - .env
networks:
  rabbitmq:
    driver: bridge
