[package]
name = "server"
version = "0.1.0"
edition = "2021"
default-run = "server"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
chrono = "0.4.38"
dotenv = "0.15.0"
envconfig = "0.10.0"
futures = "0.3.30"
futures-lite = "2.3.0"
itertools = "0.12.1"
lapin = "2.3.4"
lazy_static = "1.4.0"
log = "0.4.21"
log4rs = "1.3.0"
rand = "0.8.5"
regex = "1.10.4"
reqwest = { version = "0.12.4", features = ["json"] }
serde = { version = "1.0.199", features = ["derive"] }
serde_json = { version = "1.0.116", features = ["raw_value"] }
svix-ksuid = { version = "^0.8.0", features = ["serde"] }
tokio = { version = "1.37.0", features = ["full"] }
url = "2.5.0"

[dev-dependencies]
mockito = "1.4.0"
temp-env = "0.3.6"
test-case = "3.3.1"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "dispatcher"
path = "src/bin/dispatcher.rs"
