[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
futures = "0.3"
log = "0.4.21"
log4rs = "1.3.0"
svix-ksuid = { version = "^0.8.0", features = ["serde"] }
derive = { path = "../derive" }
url = "2.5.0"
itertools = "0.12.1"
regex = "1.10.3"
lazy_static = "1.4.0"