[package]
name = "server"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
derive = { path = "../derive" }
futures = "0.3"
itertools = "0.12.1"
lazy_static = "1.4.0"
log = "0.4.21"
log4rs = "1.3.0"
regex = "1.10.3"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.114", features = ["raw_value"] }
svix-ksuid = { version = "^0.8.0", features = ["serde"] }
url = "2.5.0"
