[package]
name = "server"
version = "0.1.0"
edition = "2021"
default-run = "server"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
derive = { path = "../derive" }
futures = "0.3"
futures-lite = "2.3.0"
itertools = "0.12.1"
lapin = "2.3.1"
lazy_static = "1.4.0"
log = "0.4.21"
log4rs = "1.3.0"
regex = "1.10.3"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.114", features = ["raw_value"] }
svix-ksuid = { version = "^0.8.0", features = ["serde"] }
tokio = { version = "1.36.0", features = ["full"] }
url = "2.5.0"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "dispatcher"
path = "src/bin/dispatcher.rs"
