@url = http://localhost:8090

### Create application
POST {{url}}/v1/application
Content-Type: application/json

{
  "name": "Dummy application"
}

> {%
    client.global.set("app_id", response.body.id);
%}

### Create endpoint
POST {{url}}/v1/application/{{app_id}}/endpoint
Content-Type: application/json

{
  "url": "http://localhost:8080",
  "topics": [
    "contact.updated",
    "contact.created"
  ]
}

### Create message
POST {{url}}/v1/application/{{app_id}}/message
Content-Type: application/json

{
  "payload": {
    "foo": "bar"
  }
}