@url = http://localhost:8090

### Health check
GET {{url}}/v1/health_check
Content-Type: application/json

### Create application
POST {{url}}/v1/application
Content-Type: application/json

{
  "name": "Dummy application"
}

> {%
    client.global.set("app_id", response.body.id);
%}

### Create endpoint
POST {{url}}/v1/application/{{app_id}}/endpoint
Content-Type: application/json

{
  "url": "http://localhost:8080",
  "topics": [
    "contact.updated",
    "contact.created"
  ]
}

> {%
    client.global.set("endpoint_id", response.body.id);
%}

### Create event
POST {{url}}/v1/application/{{app_id}}/event
Content-Type: application/json

{
  "topic": "contact.created",
  "payload": {
    "foo": "bar",
    "nested": {
      "test": [
        "123",
        "ABC"
      ]
    }
  }
}

### Disable endpoint
POST {{url}}/v1/application/{{app_id}}/endpoint/{{endpoint_id}}/disable
Content-Type: application/json

### Enable endpoint
POST {{url}}/v1/application/{{app_id}}/endpoint/{{endpoint_id}}/enable
Content-Type: application/json