name: Cargo sort
on: [ pull_request, push ]
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-sort
        run: cargo install cargo-sort
      - name: Run cargo sort
        run: cargo sort --workspace --check