name: Cargo sort
on:
  pull_request:
    paths:
      - 'Cargo.toml'
      - '**/Cargo.toml'
  push:
    paths:
      - 'Cargo.toml'
      - '**/Cargo.toml'
jobs:
  cargo_sort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-sort
        run: cargo install cargo-sort
      - name: Run cargo sort
        run: cargo sort --workspace --check
