name: Cargo sort
on:
  pull_request:
    paths:
      - 'Cargo.toml'
      - '**/Cargo.toml'
  push:
    branches:
      - master
    paths:
      - 'Cargo.toml'
      - '**/Cargo.toml'
jobs:
  cargo_sort:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/manhunto/webhooks-rs-dev:latest
      credentials:
        username: manhunto
        password: ${{ secrets.GHCR_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache setup
        uses: Swatinem/rust-cache@v2
      - name: Run cargo sort
        run: cargo sort --workspace --check
