name: Conventional Commits
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webiny/action-conventional-commits@v1.3.0
        with:
          allowed-commit-types: "feat,fix,docs,style,refactor,test,build,perf,ci,chore,revert,merge,wip,ops"
